# @package _global_

agent:
  name: bc
  _target_: agent.bc.BC
  obs_dim: ??? # to be specified later
  action_dim: ??? # to be specified later

  actor_cfg: ${diag_gaussian_actor}
  actor_lr: 3e-5
  actor_betas: [0.9, 0.999]
  actor_update_frequency: 1

  # learn temperature coefficient (disabled by default)
  learn_temp: false

  # Use either value_dice actor or normal SAC actor loss
  vdice_actor: false

diag_gaussian_actor:
  _target_: agent.sac_models.DiagGaussianActor
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
  hidden_dim: 256
  hidden_depth: 2
  log_std_bounds: [-5, 2]